target 'RETableViewManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RETableViewManagerDemo
  pod 'Masonry', '~> 1.0.0'
 
  pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git'
  pod 'RETableViewManager'
  #pod 'TZImagePickerController', '~> 1.3.2'
end
